// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddDownload(urlStr: string, title: string): $CancellablePromise<string> {
    return $Call.ByID(421089748, urlStr, title);
}

export function GetDownloads(): $CancellablePromise<$models.DownloadItem[] | null> {
    return $Call.ByID(3093261880);
}

export function GetMediaInfo(target: string): $CancellablePromise<$models.MediaInfo | null> {
    return $Call.ByID(605887497, target);
}

export function PauseDownload(id: string): $CancellablePromise<void> {
    return $Call.ByID(1028494649, id);
}

export function RemoveDownload(id: string, deleteFile: boolean): $CancellablePromise<void> {
    return $Call.ByID(3155670617, id, deleteFile);
}

export function ResumeDownload(id: string): $CancellablePromise<void> {
    return $Call.ByID(687612914, id);
}

export function ScanDownloads(): $CancellablePromise<$models.DownloadItem[] | null> {
    return $Call.ByID(4211574425);
}

export function SetWailsApp(w: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(543693278, w);
}

export function SetWindow(w: application$0.WebviewWindow | null): $CancellablePromise<void> {
    return $Call.ByID(3654517795, w);
}

export function ShowInFolder(id: string): $CancellablePromise<void> {
    return $Call.ByID(1225131967, id);
}

export function StartServer(): $CancellablePromise<void> {
    return $Call.ByID(1592333068);
}
