// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddDownload is called by the server.go when a new download request arrives
 */
export function AddDownload(url: string, typ: string, size: string, pageUrl: string, title: string): $CancellablePromise<void> {
    return $Call.ByID(421089748, url, typ, size, pageUrl, title);
}

/**
 * CancelDownload kills the process and deletes the downloaded files
 */
export function CancelDownload(id: string): $CancellablePromise<void> {
    return $Call.ByID(2532515671, id);
}

export function GetConfig(): $CancellablePromise<$models.AppConfig> {
    return $Call.ByID(1200034045);
}

/**
 * GetDownloads is exposed to frontend
 */
export function GetDownloads(): $CancellablePromise<$models.DownloadItem[] | null> {
    return $Call.ByID(3093261880);
}

export function Logf(format: string, ...args: any[]): $CancellablePromise<void> {
    return $Call.ByID(4095215453, format, args);
}

/**
 * PauseDownload kills the current download process but keeps the state so it can be resumed
 */
export function PauseDownload(id: string): $CancellablePromise<void> {
    return $Call.ByID(1028494649, id);
}

/**
 * RemoveDownload deletes the download completely from the list and database
 */
export function RemoveDownload(id: string): $CancellablePromise<void> {
    return $Call.ByID(3155670617, id);
}

/**
 * ResumeDownload re-starts a paused download
 */
export function ResumeDownload(id: string): $CancellablePromise<void> {
    return $Call.ByID(687612914, id);
}

/**
 * RetryDownload re-starts an errored or cancelled download
 */
export function RetryDownload(id: string): $CancellablePromise<void> {
    return $Call.ByID(2868588333, id);
}

export function SaveConfig(config: $models.AppConfig): $CancellablePromise<void> {
    return $Call.ByID(3442292638, config);
}

export function SetWailsApp(wailsApp: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(543693278, wailsApp);
}

export function SetWindow(w: application$0.WebviewWindow | null): $CancellablePromise<void> {
    return $Call.ByID(3654517795, w);
}

export function StartDownloadProcess(id: string, downloadUrl: string): $CancellablePromise<void> {
    return $Call.ByID(377378744, id, downloadUrl);
}

export function StartServer(): $CancellablePromise<void> {
    return $Call.ByID(1592333068);
}
