// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddDownload is called by the server.go when a new download request arrives
 */
export function AddDownload(url: string, typ: string, size: string): $CancellablePromise<void> {
    return $Call.ByID(421089748, url, typ, size);
}

/**
 * GetDownloads is exposed to frontend
 */
export function GetDownloads(): $CancellablePromise<$models.DownloadItem[] | null> {
    return $Call.ByID(3093261880);
}

export function SetWailsApp(wailsApp: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(543693278, wailsApp);
}

export function StartDownloadProcess(id: string, url: string): $CancellablePromise<void> {
    return $Call.ByID(377378744, id, url);
}

export function StartServer(): $CancellablePromise<void> {
    return $Call.ByID(1592333068);
}
