// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AppConfig {
    "customPaths": { [_ in string]?: string } | null;
    "concurrentFragments": number;
}

export interface DownloadItem {
    "id": string;
    "url": string;
    "type": string;
    "size": string;

    /**
     * "pending", "downloading", "paused", "completed", "error", "cancelled"
     */
    "status": string;
    "pageUrl": string;

    /**
     * The path to the file on disk
     */
    "destination"?: string;
    "title": string;
}
