// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface DownloadItem {
    "id": string;
    "url": string;
    "type": string;
    "size": string;

    /**
     * "pending", "downloading", "completed", "error"
     */
    "status": string;
}
