// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AppConfig {
    "customPaths": { [_ in string]?: string } | null;
    "concurrentFragments": number;
    "enableProbe": boolean;
    "probeSizeMB": number;
}

export interface DownloadItem {
    "id": string;
    "url": string;
    "type": string;
    "size": string;

    /**
     * "pending", "downloading", "paused", "completed", "error", "cancelled"
     */
    "status": string;
    "pageUrl": string;

    /**
     * The path to the file on disk
     */
    "destination"?: string;
    "title": string;

    /**
     * Selected format ID e.g. "137+bestaudio" or "140"
     */
    "formatId"?: string;

    /**
     * Short live status line e.g. "Downloading webpage", "Moving file..."
     */
    "statusMsg"?: string;
    "progress"?: number;
    "speed"?: string;
    "downloadedSize"?: string;
    "totalSize"?: string;
}

export interface YouTubeFormat {
    "formatId": string;
    "ext": string;
    "resolution": string;
    "fps": number;
    "filesize": number;
    "tbr": number;
    "vcodec": string;
    "acodec": string;
    "formatNote": string;
    "format": string;
}
